### ISSUE TITLE
Feature request: Support for "imports" field in "package.json" for "node" template

### ISSUE THREAD

**Issue by GabenGar** [jsimck/jsconfig.json#24]
Node has [its own way to set path aliases](https://nodejs.org/api/packages.html#packages_subpath_imports) now, so it would be nice if the package would read them too like it does with webpack template.

**Comment by jsimck** [comment]
Hi, thanks for the input, sounds like a great addition, I'll definitely have a look at that when as soon as I have a chance.

**Comment by jsimck** [comment]
I've just released v2.2.0, which implements support for node `imports` field. There's support only for the subpath patterns (strings). Let me know if this is what you had in mind. Personally I didn't have a chance to used this option yet... but hopefully read the documentation right.
